services:
  demo:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:alpine
    volumes:
      - ./psql-init.sql:/docker-entrypoint-initdb.d/psql-init.sql:ro
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
    ports:
      - 5430:5432